name: py_asciimath
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - appdirs
  - attrs
  - black
  - ca-certificates
  - certifi
  - click
  - entrypoints
  - flake8
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - mccabe
  - mypy_extensions
  - ncurses
  - openssl
  - pathspec
  - pip
  - pycodestyle
  - pyflakes
  - python
  - readline
  - regex
  - setuptools
  - sqlite
  - tk
  - toml
  - typed-ast
  - typing_extensions
  - wheel
  - xz
  - zlib
  - pip:
    - 3to2
    - bleach
    - cffi
    - chardet
    - coverage
    - cryptography
    - distlib
    - docopt
    - docutils
    - filelock
    - future
    - idna
    - jeepney
    - keyring
    - lark-parser
    - packaging
    - pkginfo
    - pluggy
    - py
    - pycparser
    - pygments
    - pyparsing
    - readme-renderer
    - requests
    - requests-toolbelt
    - secretstorage
    - six
    - tox
    - tqdm
    - twine
    - urllib3
    - virtualenv
    - webencodings

